# Generated by Django 2.2.5 on 2019-09-22 12:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
        migrations.AlterField(
            model_name='userfoodhistory',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 22, 12, 37, 15, 123388, tzinfo=utc)),
        ),
    ]
