# Generated by Django 2.2.6 on 2019-11-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbodyparameters',
            name='user_height',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='userbodyparameters',
            name='user_weight',
            field=models.IntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='usernutritionstarget',
            name='target_calories',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='usernutritionstarget',
            name='target_carbohydrates',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='usernutritionstarget',
            name='target_fats',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='usernutritionstarget',
            name='target_proteins',
            field=models.IntegerField(default=100),
        ),
    ]
