# Generated by Django 2.2.5 on 2019-10-06 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='food',
        ),
        migrations.CreateModel(
            name='FoodDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_weight', models.DecimalField(decimal_places=3, default=100, max_digits=6)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Meal')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='food',
            field=models.ManyToManyField(through='accounts.FoodDetails', to='food.Food'),
        ),
    ]
