# Generated by Django 2.2.5 on 2019-10-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191006_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfoodhistory',
            name='meal',
        ),
        migrations.AddField(
            model_name='userfoodhistory',
            name='meal',
            field=models.ManyToManyField(to='accounts.Meal'),
        ),
    ]
