# Generated by Django 2.2.6 on 2019-11-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191106_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbodyparameters',
            name='user_bmi',
            field=models.DecimalField(decimal_places=2, default=23.15, max_digits=4),
        ),
    ]
