# Generated by Django 2.2.5 on 2019-09-22 12:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190922_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfoodhistory',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 22, 12, 41, 6, 355185, tzinfo=utc)),
        ),
    ]
