# Generated by Django 2.2.5 on 2019-09-22 15:01

import accounts.models
import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import enumchoicefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190922_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meal_type',
            field=enumchoicefield.fields.EnumChoiceField(enum_class=accounts.models.MealType, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.Food'),
        ),
        migrations.AlterField(
            model_name='userfoodhistory',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 22, 15, 1, 55, 286874, tzinfo=utc)),
        ),
    ]
