# Generated by Django 2.2.6 on 2019-11-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userbodyparameters_user_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbodyparameters',
            name='user_bmi',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=4),
        ),
        migrations.AlterField(
            model_name='usernutritionstarget',
            name='target_calories',
            field=models.IntegerField(default=1910),
        ),
        migrations.AlterField(
            model_name='usernutritionstarget',
            name='target_carbohydrates',
            field=models.IntegerField(default=270),
        ),
        migrations.AlterField(
            model_name='usernutritionstarget',
            name='target_fats',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='usernutritionstarget',
            name='target_proteins',
            field=models.IntegerField(default=50),
        ),
    ]
