# Generated by Django 2.2.5 on 2019-09-22 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190922_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfoodhistory',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 22, 15, 8, 44, 574539, tzinfo=utc)),
        ),
    ]
