# Generated by Django 2.2.6 on 2019-11-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191108_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbodyparameters',
            name='user_bmi',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='userbodyparameters',
            name='user_height',
            field=models.IntegerField(default=180),
        ),
        migrations.AlterField(
            model_name='userbodyparameters',
            name='user_weight',
            field=models.IntegerField(default=75),
        ),
    ]
