# Generated by Django 2.2.5 on 2019-09-22 15:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190922_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfoodhistory',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 9, 22, 15, 19, 20, 391456, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='userfoodhistory',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Meal'),
        ),
    ]
