# Generated by Django 2.2.5 on 2019-09-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(default='', max_length=255)),
                ('energy_value', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fats', models.DecimalField(decimal_places=3, max_digits=6)),
                ('saturated_fats', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=3, max_digits=6)),
                ('sugars', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('proteins', models.DecimalField(decimal_places=3, max_digits=6)),
                ('salt', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
            ],
        ),
    ]
