# Generated by Django 2.2.6 on 2019-11-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='energy_value',
            field=models.IntegerField(),
        ),
    ]
